### ISSUE TITLE
Count example in the docs seems wrong

### ISSUE THREAD

**Issue by pdonorio** [schapman1974/tinymongo#56]
Hello! Thanks for the great lib ^_^

I've been testing a bit the examples, 
and found out that 
```python
# Getting the total of records
db.users.count()
```
[in the README](https://github.com/schapman1974/tinymongo/blame/master/README.md#L78) doesn't work for me, while `db.users.find().count()` does.

Am I doing something wrong or is the docs to fix?
Thank you,
have the greatest day

**Comment by schapman1974** [comment]
Strange in the background its doing a .find().count().  Can you give a small example that breaks?
https://github.com/schapman1974/tinymongo/blob/master/tinymongo/tinymongo.py#L155

**Comment by pdonorio** [comment]
Sure, to have it on a fresh install I checked with:

```bash
docker run --rm -it python:3.6-alpine ash

$ pip install tinymongo
# [...]

$ python
Python 3.6.10 (default, Jan 18 2020, 02:57:08)
[GCC 9.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from tinymongo import TinyMongoClient
>>> collection = TinyMongoClient().mydb.users
>>> collection.find().count()
0
>>> collection.count()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'TinyMongoCollection' object is not callable
>>>
```

Same with Python 3.7 and 3.8.

**Comment by schapman1974** [comment]
Show me where i'm going wrong in my testing
https://github.com/schapman1974/tinymongo/blob/master/demo.py#L45
I added count functionality to the demo.py and everything runs as expected.
Is this maybe when there is no data that you are doing this.  Let me know. If the functionality there differs from how MongoCollection works we can certainly fix that.

**Comment by davidlatwe** [comment]
Hi @schapman1974  and @pdonorio 

I just saw the line `$ pip install tinymongo` in the comment so I think the problem is that the `tinymongo` module @pdonorio had was installed by `pip`, which is a very very old version (back to 2017).

Try `git clone` or `pip install git+https://github.com/schapman1974/tinymongo.git` to grab the latest and the issue should be gone.

**Comment by pdonorio** [comment]
@davidlatwe you are right:

```bash
docker run --rm -it python:3.8-alpine ash

$ apk add git
# [...]
$ pip install git+https://github.com/schapman1974/tinymongo.git
# [...]
Successfully installed pymongo-3.10.1 tinydb-3.15.2 tinydb-serialization-1.0.4 tinymongo-0.2.1
$ python
Python 3.8.2 (default, Mar 24 2020, 02:56:01)
[GCC 9.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from tinymongo import TinyMongoClient
>>> collection = TinyMongoClient().mydb.users
>>> collection.count()
0
```

So the docs for the current stable are not to be found in the README, obviously, sorry. My fault.

Two things as side notes:
1. should a new version be released on Pypi if the current one is too old? 
2. I've just find out that pymongo API moved from `query_set.count()` to `collection. count_documents(query)`, as shown in: https://api.mongodb.com/python/current/tutorial.html#counting. Maybe you want to reflect this change too? 

I can open other issues for those if you like, and try to help out with a PR for the second one.

I'll close this one as we've found I was wrong, thanks!

**Comment by schapman1974** [comment]
Yeah happy to review PR for that.  I can get PyPi updated this week sometime
